<template>
  <img class="more" src="/src/assets/indexico/more.svg" alt="更多" @click.stop="onShow" />
  <div class="popover" :class="transition">
    <div class="popper-arrow"></div>
    <div class="menu-list">
      <div class="menu-item" v-for="item in menuList">
        <img :src="item.ico" :alt="item.title" />
        <div class="title">
          {{ item.title }}
        </div>
      </div>
    </div>
  </div>

  <div class="click-block" v-show="show" @click="show = false"></div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'

const menuList = ref([
  { title: '发起群聊', ico: '/src/assets/indexico/more.svg' },
  { title: '添加朋友', ico: '/src/assets/indexico/more.svg' },
  { title: '扫一扫', ico: '/src/assets/indexico/more.svg' },
  { title: '收付款', ico: '/src/assets/indexico/more.svg' },
  { title: '帮助与反馈', ico: '/src/assets/indexico/more.svg' }
])
const show = ref(false)
let flag = ref(true)

const transition = computed(() => {
  if (flag.value) {
    return ''
  }
  return show.value ? 'scale-in-tr' : 'scale-out-tr'
})

const onShow = () => {
  if (flag.value) {
    flag.value = false
  }
  show.value = true
}

onMounted(() => {})
</script>

<style lang="less" scoped>
img.more {
  position: relative;
  width: 50rem;
  height: 50rem;
}

.popover {
  width: 300rem;
  height: 500rem;
  border-radius: 15rem;
  position: absolute;
  top: 80rem;
  right: -15rem;
  z-index: 2;
  background-color: #4c4c4c;
  transform: scale(0);

  .popper-arrow {
    position: absolute;
    top: -20rem;
    right: 15rem;

    border-left: 25rem solid transparent;
    border-right: 25rem solid transparent;
    border-bottom: 30rem solid #4c4c4c;
  }

  .menu-list {
    height: 100%;
    .menu-item {
      height: 20%;
      color: #fefefe;
      display: flex;
      align-items: center;

      img {
        width: 60rem;
        height: 60rem;
        margin: 0 20rem 0 25rem;
      }
      .title {
        width: 195rem;
        height: 100%;
        display: flex;
        align-items: center;
        font-size: 30rem;
      }
    }
    & .menu-item:not(:last-child) {
      .title {
        border-bottom: #e8e8e83b solid 1rem;
      }
    }
  }
}

.click-block {
  width: 100vw;
  height: 100vh;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
}

.scale-in-tr {
  -webkit-animation: scale-in-tr 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-tr 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-20 22:53:32
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-tr
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-tr {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}
@keyframes scale-in-tr {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}

.scale-out-tr {
  -webkit-animation: scale-out-tr 0.2s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  animation: scale-out-tr 0.2s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-20 22:54:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-tr
 * ----------------------------------------
 */
@-webkit-keyframes scale-out-tr {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}
@keyframes scale-out-tr {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}
</style>